AGENT_CONFIG:
  agent_name: GlasHoch_Rangers_imitation
  config_name: default
  state_dim: [7, 9, 9]
  action_dim: 6
  batch_size: 64
  memory_size: 10000
  burnin: 5000
  learn_evry: 10
  sync_evry: 1000
  gamma: 0.95
  save_every: 100000
  curr_step: 0
  exploration_rate: 1
  exploration_rate_decay: 0.999999
  exploration_rate_min: 0.05
  imitation_learning: True
  imitation_learning_rate: 0.8
  imitation_learning_decay: 0.999999
  imitation_learning_min: 0.2
  imitation_learning_expert: rule_based_agent
  load: False
  load_path: todo
  learning_rate: 0.001
  lr_scheduler_step: 1000
  lr_scheduler_gamma: 0.99
  lr_scheduler_min: 0.00025
  exploration_method: epsilon-greedy
  loss_fn: MSE
  lr_scheduler: False
  draw_plot: False
  draw_plot_every: 10

REWARD_CONFIG:
  MOVED_LEFT: 1
  MOVED_RIGHT: 1
  MOVED_UP: 1
  MOVED_DOWN:  1
  WAITED: -10
  INVALID_ACTION: -10
  BOMB_DROPPED: 2
  BOMB_EXPLODED: 0
  CRATE_DESTROYED: 5
  COIN_FOUND: 5
  COIN_COLLECTED: 5
  KILLED_OPPONENT: 10
  KILLED_SELF: -50
  GOT_KILLED: -10
  MOVED_TOWARDS_COIN_CLUSTER: 2
  MOVED_TOWARDS_ENEMY: 1
  TRAPPED_ENEMY: 5
  BOMB_NEAR_CRATE: 2
  BOMB_NEAR_ENEMY: 3
  OPPONENT_ELIMINATED: 1
  SURVIVED_ROUND: 10
  ALREADY_VISITED: -0.5
  MOVED_OUT_OF_DANGER: 1
