AGENT_CONFIG:
  state_dim: (6,9,9)
  action_dim: 6
  batch_size: 32
  memory_size: 1000
  burnin: 100
  learn_evry: 4
  sync_evry: 10
  gamma: 0.95
  save_every: 500
  curr_step: 0

REWARD_CONFIG:
  MOVED_LEFT: 1
  MOVED_RIGHT: 1
  MOVED_UP: 1
  MOVED_DOWN: 1
  WAITED: -1
  INVALID_ACTION: -1
  BOMB_DROPPED: 1
  BOMB_EXPLODED: 1
  CRATE_DESTROYED: 1
  COIN_FOUND: 1
  COIN_COLLECTED: 5
  KILLED_OPPONENT: 10
  KILLED_SELF: -5
  GOT_KILLED: -10
  ALREADY_VISITED: -2
  MOVED_TOWARDS_COIN_CLUSTER: 2
  MOVED_TOWARDS_ENEMY: 1
  TRAPPED_ENEMY: 5
  BOMB_NEAR_CRATE: 2
  BOMB_NEAR_ENEMY: 3
  BOMB_NEXT_TO_ENEMY: 5
