AGENT_CONFIG:
  state_dim: [6, 9, 9]
  action_dim: 6
  batch_size: 1
  memory_size: 1000
  burnin: 5
  learn_evry: 20
  sync_evry: 40
  gamma: 0.95
  save_every: 500
  curr_step: 0
  exploration_rate: 0.4
  exploration_rate_decay: 0.999
  exploration_rate_min: 0.025
  load: False
  load_path: ./models/agent_0.pth
  learning_rate: 0.00025
  lr_scheduler_step: 1000  # Adjust as needed
  lr_scheduler_gamma: 0.9  # Adjust as needed
  exploration_method: epsilon-greedy

REWARD_CONFIG:
  MOVED_LEFT: 0
  MOVED_RIGHT: 0
  MOVED_UP: 0
  MOVED_DOWN: 0
  WAITED: -2
  INVALID_ACTION: -100
  BOMB_DROPPED: 1
  BOMB_EXPLODED: 1
  CRATE_DESTROYED: 1
  COIN_FOUND: 5
  COIN_COLLECTED: 5
  KILLED_OPPONENT: 10
  KILLED_SELF: -5
  GOT_KILLED: -10
  ALREADY_VISITED: -2
  MOVED_TOWARDS_COIN_CLUSTER: 2
  MOVED_TOWARDS_ENEMY: 1
  TRAPPED_ENEMY: 5
  BOMB_NEAR_CRATE: 2
  BOMB_NEAR_ENEMY: 3
  BOMB_NEXT_TO_ENEMY: 5
  OPPONENT_ELIMINATED: 1
  SURVIVED_ROUND: 10
